apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll-ui
  template:
    metadata:
      labels:
        app: payroll-ui
    spec:
      containers:
      - name: payroll-ui
        image: manjukundargi/pay-ui
        ports:
        - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: payroll-service
spec:
  selector:
    app: payroll-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer